### ISSUE TITLE
Add AutoDoor to integration

### ISSUE THREAD

**Issue by Ayuus** [bhuebschen/liebherr#33]
Hello, in the Liebherr release notes (june 2025), I read that Autodoor is supported. Finally! Could you please make this available via the integration?

**Comment by black1nero** [comment]
I'm waiting for autodoor feature too. I saw it in patch notes for 0.9 but its not working.

**Comment by skatsavos** [comment]
Hi i pushed the code for AutoDoor following the liebherr pi instructions. Unfortunately my fridge does not support this feature so i can test it.
Can you pull the https://github.com/bhuebschen/liebherr/pull/34 and test it and provide some feedback?

**Comment by black1nero** [comment]
I barely know what I'm doing but ill try to help.
IceMaker is working, AutoDoor is detected but not working - state shows unknown, as option i only have "OPEN" which causes this popup: "Failed to perform the action select/select_option. asdict() should be called on dataclass instances"

**Comment by skatsavos** [comment]
I made some changes and uploaded a newer version, if you have any further issues try enable debug logging and post your logs here

**Comment by black1nero** [comment]
Still not working, getting this popup message: Failed to perform the action cover/open_cover. asdict() should be called on dataclass instances

This is what i can see in logs:

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:258
integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 8:58:45 PM (6 occurrences)
Last logged: 9:08:29 PM

[140513256443712] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 258, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2799, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2842, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1011, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1083, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/liebherr/cover.py", line 129, in async_open_cover
    await self._api.set_value(self._appliance["deviceId"], self._control["name"], payload)
  File "/config/custom_components/liebherr/__init__.py", line 213, in set_value
    payload = asdict(value)
  File "/usr/local/lib/python3.13/dataclasses.py", line 1358, in asdict
    raise TypeError("asdict() should be called on dataclass instances")
TypeError: asdict() should be called on dataclass instances

**Comment by skatsavos** [comment]
Yes that was an issue, i pushed an update that propably should fix it. I test it also with mock data and it seems ok, unfortunately i cannot test it with real data end to end since i do not have this feature in my fridge. To get logs -> enable debug logging then do some stuf then disable and when you disable it it will download a log file. But i think it will work now!

**Comment by black1nero** [comment]
Awesome, it works now, thank you very much!

**Comment by Ayuus** [comment]
I downloaded code from https://github.com/skatsavos/liebherr but I do not see any Autodoor reference in Liebherr integration. I do see new IceMaker control. What am I doing wrong here?

**Comment by skatsavos** [comment]
This was because you download my forked project (you could simply download the code from pull request in here) but from main branch which was not updated. I update it so if you pull again it will fetch all the updated code.

**Comment by Ayuus** [comment]
Downloaded from other branch, works for me, thanks!

**Comment by Ayuus** [comment]
Some feedback from my side:

Opening/closing works!
State is not updated correctly: after opening state still says closed (during opening, state says opening)
AutodoorControl sensors (3 in total) report unavailable

**Comment by skatsavos** [comment]
Regarding the sensors: The sensors are disabled by default since although the bhuebschen have included them, they actually not supported by liebherr api.
Is it the state of the sensor not updated  or the state of the door (cover entity) ? 
Can you notice if it is updated but slower because bhuebschen has put a 5s delay and i am not sure why it included.
Maybe if you provided the debug logs i will be able to debug and solve it if i can(the state of the sensor).

**Comment by Ayuus** [comment]
Regarding sensors: OK, clear, I disable them again.
Regarding state: I would suggest changing to opening immediately, and to open after 5s (which is about the duration my fridge needs to open the door and allow closing again. I just tested manually: closing while it is still opening does not work.

Edit: after opening manually: cover state still reports closed.

Edit 2: if I close via cover.close, cover state starts to report open, and keeps reporting open.

**Comment by skatsavos** [comment]
I checked again the code and i think the issue because the code handles the autodoor sensor (the entity that shows the status only) the same way with other sensors eg. supercool but i can see these are returning from liebherr api true or false but autodoor returns CLOSED, OPEN, MOVING which might explain why you are not seeing the currect status

**Comment by skatsavos** [comment]
I noticed that the sensor file was not used up to now. I made some refactoring, you can get the updates and test them. I noticed that at least for icemaker needs delay 5sec otherwise the status does not update.
I placed 3s delay for the status of autodoor to be updated, but if you think it is too much i can send you an update without and test it.

**Comment by Ayuus** [comment]
Hi,

Downloaded this morning via HACS, checked that I have latest file and restarted HA>
Sensor still does not display correct status. I opened and closed the fridge twice.
Status: CLOSED-MOVING-CLOSED and CLOSED-OPEN-CLOSED
I would have expected CLOSED-MOVING-OPEN-MOVING-CLOSED twice.
Same for cover status: does change, but too late and not consistent with actual situation.
When door is opened, cover status keeps saying opening. When door is closed again, cover reports open very short time, then opening (when door is actually closing), and finally closed.

REgards, Ronald

Edit: I would be glad to test a version without the delay!

**Comment by bhuebschen** [comment]
i will merge the PR from skatsavos and mine today

**Comment by skatsavos** [comment]
I think it needs some adjustments because libherr api does not update its status immediately. @bhuebschen i will provide some improvements (naming) later today for the icemaker.

**Comment by skatsavos** [comment]
The issue is tricky because it is affected by the slow update rate of liebeherr api. 
I applied 2 changes which theoritically can provided the transitions.
Unfortunatelyi cannot test since no any other sensor has similar behaviour. And thus it is difficult to provide an appropriate solution without testing it with a fridge that supports this feature.
If it is better we can keep them, if it is worse we can remove the addional changes. 
Otherwise we have to make other changes with @bhuebschen  permittion such as increase the polling rate.
@bhuebschen you can wait the feedback from @Ayuus and merge the changes when you ready (or leave any comments so we can discuss them) The icemaker feature works perfectly in me as it is.

**Comment by Ayuus** [comment]
[@skatsavos](https://github.com/skatsavos) what more feedback is needed from my side?

**Comment by skatsavos** [comment]
I pushed some new changes yesterday!

**Comment by Ayuus** [comment]
Ah. ok. Downloaded, checked that files were actually updated (with debounce) and restarted HA.
Opened and closed fridge manually (keep open 10 seconds) first time: AutoDoorControl sensor state switches to MOVING after I closed the fridge. 30s later, reports CLOSED. Second time: sensor was not updated at all.
Opened and closed fridge by using switch in Integrtion (keep open 10 seconds): switch reports closed after opening, and when I click on Close, switch says opening. When door is closed: switch says Open for about 30s and then says Closed.

Edit: set debounce to 0, restarted HA: same results, in the sens that both sensor and switch state are not updated consistent with actual state. Easiest way to test is just opening the fridge and observe that both switch state and sensor value still report Closed.

Edit 2: sensor value and switch state do not report the same value. Both values are updated too late, both entities sometimes skip state MOVING.

Edit 3: switch always works: closes when open, opens when closed, regardless of reported switch state/sensor value.

**Comment by Ayuus** [comment]
There seems to be a 30s delay in status reporting.

**Comment by skatsavos** [comment]
I think the slow update rate of lieherr api will not provide any room for improvements. I reverted the last changes. I think @bhuebschen can review make his changes and provide a new version with the latest additions

**Comment by 74smoky** [comment]
I played around with the HomeAPI's Autodoor function directly on developer.liebherr.com. I also had the SmartDevice app open. I was able to see the actual state almost simultaneously in the HomeAPI controls, especially the MOVING state. To put it briefly, I can't confirm the 30-second time latency discussed here in the HomeAPI itself.

https://developer.liebherr.com/apis/smartdevice-homeapi/swagger-ui/#/Manage%20Controls/triggerAutoDoor
